[EAG-203] SelectWidget: support getting options from an endpoint.
CareCloud/react-jsonschema-form pull request #11
Opened 2018-01-12 13:57 UTC by jnorris-carecloud

**Ticket**: https://jira.carecloud.com/browse/EAG-203
**Reviewers**: @amartin-carecloud @rcarranza-carecloud @jleyba-carecloud

2018-01-12 14:10 UTC, jleyba-carecloud commented on src/components/widgets/SelectWidget.js
> +    return fetch(url, { headers })
Are we using Fetch for any specific reason? It can be a pain managing errors.

2018-01-12 14:13 UTC, jleyba-carecloud approved these changes

2018-01-12 15:08 UTC, rcarranza-carecloud requested changes

2018-01-12 15:08 UTC, rcarranza-carecloud commented on src/components/widgets/SelectWidget.js
> +    const { async } = this.props.options;
Given that you're handling **props** directly, you can omit _"this"_.

2018-01-12 15:08 UTC, rcarranza-carecloud commented on src/components/widgets/SelectWidget.js
> +    const options = this.props.options;
To avoid potential issues here I would do:
```javascript
const {options={}} = this.props;
const {async=false} = options;
```

2018-01-12 15:08 UTC, rcarranza-carecloud commented on src/components/widgets/SelectWidget.js
> +    const options = this.props.options;
I've checked the PropTypes so this is not necessary.

2018-01-12 18:01 UTC, jnorris-carecloud commented on src/components/widgets/SelectWidget.js
> +    return fetch(url, { headers })
What's the issue with the errors?

I'm using fetch because I don't really want to add any library to handle requests, since there wouldn't be much customization on this.

2018-01-12 18:02 UTC, jnorris-carecloud commented on src/components/widgets/SelectWidget.js
> +    const { async } = this.props.options;
True that.

2018-01-12 18:03 UTC, jnorris-carecloud commented on src/components/widgets/SelectWidget.js
> +    const options = this.props.options;
Are you saying that it's ok to leave as is?

2018-01-12 18:29 UTC, rcarranza-carecloud commented on src/components/widgets/SelectWidget.js
> +    const options = this.props.options;
Yes. If the developer use this correctly (following the propTypes) there is no way this can blow up.

2018-01-12 20:18 UTC, jnorris-carecloud commented on src/components/widgets/SelectWidget.js
> +    const options = this.props.options;
Ok ty!

2018-01-12 20:23 UTC, jnorris-carecloud commented
@rcarranza-carecloud I commited small changes, please review them.

2018-01-15 21:45 UTC, rcarranza-carecloud approved these changes

2018-01-15 21:50 UTC, merged